/home/tech4good/my-bench/apps/frappe/frappe/build.py:7: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.spawn import find_executable
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/tech4good/my-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/tech4good/my-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/tech4good/my-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/tech4good/my-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/tech4good/my-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/tech4good/my-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/tech4good/my-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
/home/tech4good/my-bench/apps/frappe/frappe/build.py:7: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.spawn import find_executable
/home/tech4good/my-bench/apps/frappe/frappe/build.py:7: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.spawn import find_executable
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/tech4good/my-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/tech4good/my-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/tech4good/my-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/tech4good/my-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/tech4good/my-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/tech4good/my-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/tech4good/my-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
/home/tech4good/my-bench/apps/frappe/frappe/build.py:7: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.spawn import find_executable
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/tech4good/my-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/tech4good/my-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/tech4good/my-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/tech4good/my-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/tech4good/my-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/tech4good/my-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/tech4good/my-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
/home/tech4good/my-bench/apps/frappe/frappe/build.py:7: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.spawn import find_executable
2023-08-06 22:10:25,174 Traceback (most recent call last):
  File "/home/tech4good/my-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1013, in perform_job
    rv = job.perform()
  File "/home/tech4good/my-bench/env/lib/python3.10/site-packages/rq/job.py", line 709, in perform
    self._result = self._execute()
  File "/home/tech4good/my-bench/env/lib/python3.10/site-packages/rq/job.py", line 732, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/home/tech4good/my-bench/apps/frappe/frappe/utils/background_jobs.py", line 147, in execute_job
    retval = method(**kwargs)
  File "/home/tech4good/my-bench/apps/frappe/frappe/core/doctype/user/user.py", line 1124, in create_contact
    contact.insert(
  File "/home/tech4good/my-bench/apps/frappe/frappe/model/document.py", line 257, in insert
    self._validate_links()
  File "/home/tech4good/my-bench/apps/frappe/frappe/model/document.py", line 910, in _validate_links
    frappe.throw(_("Could not find {0}").format(msg), frappe.LinkValidationError)
  File "/home/tech4good/my-bench/apps/frappe/frappe/__init__.py", line 505, in throw
    msgprint(
  File "/home/tech4good/my-bench/apps/frappe/frappe/__init__.py", line 480, in msgprint
    _raise_exception()
  File "/home/tech4good/my-bench/apps/frappe/frappe/__init__.py", line 435, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.LinkValidationError: Could not find User Id: anand.biniya@gmail.com

/home/tech4good/my-bench/env/lib/python3.10/site-packages/botocore/httpsession.py:18: DeprecationWarning: 'urllib3.contrib.pyopenssl' module is deprecated and will be removed in a future release of urllib3 2.x. Read more in this issue: https://github.com/urllib3/urllib3/issues/2680
  from urllib3.contrib.pyopenssl import orig_util_SSLContext as SSLContext
/home/tech4good/my-bench/env/lib/python3.10/site-packages/botocore/httpsession.py:18: DeprecationWarning: 'urllib3.contrib.pyopenssl' module is deprecated and will be removed in a future release of urllib3 2.x. Read more in this issue: https://github.com/urllib3/urllib3/issues/2680
  from urllib3.contrib.pyopenssl import orig_util_SSLContext as SSLContext
/home/tech4good/my-bench/env/lib/python3.10/site-packages/botocore/httpsession.py:18: DeprecationWarning: 'urllib3.contrib.pyopenssl' module is deprecated and will be removed in a future release of urllib3 2.x. Read more in this issue: https://github.com/urllib3/urllib3/issues/2680
  from urllib3.contrib.pyopenssl import orig_util_SSLContext as SSLContext
fatal: No remote configured to list refs from.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/tech4good/my-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/tech4good/my-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/tech4good/my-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/tech4good/my-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/tech4good/my-bench/env/lib/python3.10/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/tech4good/my-bench/env/lib/python3.10/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/tech4good/my-bench/env/lib/python3.10/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
/home/tech4good/my-bench/apps/frappe/frappe/build.py:7: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.spawn import find_executable
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/tech4good/my-bench/env/lib/python3.10/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/tech4good/my-bench/env/lib/python3.10/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/tech4good/my-bench/env/lib/python3.10/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/tech4good/my-bench/env/lib/python3.10/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/tech4good/my-bench/env/lib/python3.10/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/tech4good/my-bench/env/lib/python3.10/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
/home/tech4good/my-bench/apps/frappe/frappe/build.py:7: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.spawn import find_executable
/home/tech4good/my-bench/env/lib/python3.10/site-packages/botocore/httpsession.py:18: DeprecationWarning: 'urllib3.contrib.pyopenssl' module is deprecated and will be removed in a future release of urllib3 2.x. Read more in this issue: https://github.com/urllib3/urllib3/issues/2680
  from urllib3.contrib.pyopenssl import orig_util_SSLContext as SSLContext
fatal: No remote configured to list refs from.
/home/tech4good/my-bench/apps/frappe/frappe/build.py:7: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.spawn import find_executable
